const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_VAITRO_SUCCESS: 'FETCH_VAITRO_SUCCESS',
    FETCH_VAITRO_FAIL: 'FETCH_VAITRO_FAIL',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIL: 'FETCH_ALL_USER_FAIL',

    FETCH_TOP_STAFF_SUCCESS: 'FETCH_TOP_STAFF_SUCCESS',
    FETCH_TOP_STAFF_FAIL: 'FETCH_TOP_STAFF_FAIL',

    FETCH_ALL_STAFF_SUCCESS: 'FETCH_ALL_STAFF_SUCCESS',
    FETCH_ALL_STAFF_FAIL: 'FETCH_ALL_STAFF_FAIL',

    SAVE_DETAIL_STAFF_SUCCESS: 'SAVE_DETAIL_STAFF_SUCCESS',
    SAVE_DETAIL_STAFF_FAIL: 'SAVE_DETAIL_STAFF_FAIL',

    FETCH_ALLCODE_SCHEDULE_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_FAIL: 'FETCH_ALLCODE_SCHEDULE_FAIL',

    GET_ALL_BOOK_SUCCESS: 'GET_ALL_BOOK_SUCCESS',
    GET_ALL_BOOK_FAIL: 'GET_ALL_BOOK_FAIL',

    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_FAIL: 'CREATE_BOOK_FAIL',

    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAIL: 'DELETE_BOOK_FAIL',

    UPDATE_BOOK_SUCCESS: 'UPDATE_BOOK_SUCCESS',
    UPDATE_BOOK_FAIL: 'UPDATE_BOOK_FAIL',

    FETCH_CHUYEN_MUC_SUCCESS: 'FETCH_CHUYEN_MUC_SUCCESS',
    FETCH_CHUYEN_MUC_FAIL: 'FETCH_CHUYEN_MUC_FAIL',

    CREATE_CATEGORY_SUCCSESS: 'CREATE_CATEGORY_SUCCSESS',
    CREATE_CATEGORY_FAIL: 'CREATE_CATEGORY_FAIL',

    DELETE_CATEGORY_SUCCSESS: 'DELETE_CATEGORY_SUCCSESS',
    DELETE_CATEGORY_FAIL: 'DELETE_CATEGORY_FAIL',

    UPDATE_CATEGORY_SUCCSESS: 'UPDATE_CATEGORY_SUCCSESS',
    UPDATE_CATEGORY_FAIL: 'UPDATE_CATEGORY_FAIL',

    FETCH_ALL_KINDOFBOOK_SUCCSESS: 'FETCH_ALL_KINDOFBOOK_SUCCSESS',
    FETCH_ALL_KINDOFBOOK_FAIL: 'FETCH_ALL_KINDOFBOOK_FAIL',

    CREATE_KINDOFBOOK_SUCCSESS: 'CREATE_KINDOFBOOK_SUCCSESS',
    CREATE_KINDOFBOOK_FAIL: 'CREATE_KINDOFBOOK_FAIL',

    DELETE_KINDOFBOOK_SUCCSESS: 'DELETE_KINDOFBOOK_SUCCSESS',
    DELETE_KINDOFBOOK_FAIL: 'DELETE_KINDOFBOOK_FAIL',

    UPDATE_KINDOFBOOK_SUCCSESS: 'UPDATE_KINDOFBOOK_SUCCSESS',
    UPDATE_KINDOFBOOK_FAIL: 'UPDATE_KINDOFBOOK_FAIL',


})

export default actionTypes;